excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Gopaljeepurwar.github.io
title: Gopal Jee Purwar
tagline: A log of everyday life
description: My awesome new site
paginate: 5